### PR TITLE
Add support for sixth MCOS segment introduced in R2023b.

### PR DESCRIPTION
**Pull request by nedtwigg**
In MATLAB R2023b, some of the files in the examples now have new data in the MCOS section. As in previous attempts, it's not clear what's in these sections, but it's pretty straightforward to at least continue to parse the data we have been able to get in the past.

### CODE REVIEW

**Comment by ennerf** [comment]
Thanks for your continuing support 👍

**Comment by ennerf** [comment]
I just tried to release it as `0.5.15`, but it looks like Sonatype may be having some issues. I'll try again later.

**Comment by nedtwigg** [comment]
Thanks for the quick merge! Any chance Sonatype is alive today?

**Comment by ennerf** [comment]
it just went through 👍

**Comment by nedtwigg** [comment]
Thanks!

**Pull request merged**
