### PR TITLE
Allow extension of Mat5Reader with custom filters

### PR DESCRIPTION
**Pull request by MieszkoMakuch**
Changes allow to extend Mat5Reader class and adding custom filters as described in #69 

Here is example subclass of `Mat5Reader` that adds new filters that enable to read files mentioned in #69 partially.

The added filters include:
- `CatalogStructFilter` - allows reading selected variables from matlab files, including those nested inside other structures.
- `CellFilter` - allows extracting only selected cells from a matlab file.

```java
package pl.cyfronet.insilicolab.server.model.data.reader.catalog;

import pl.cyfronet.insilicolab.shared.model.data.object.catalog.DataCatalog;
import us.hebi.matlab.mat.format.Mat5Reader;
import us.hebi.matlab.mat.format.Mat5Tag;
import us.hebi.matlab.mat.format.Mat5Type;
import us.hebi.matlab.mat.types.Array;
import us.hebi.matlab.mat.types.Source;
import us.hebi.matlab.mat.util.Casts;

import java.io.IOException;
import java.util.List;

import static us.hebi.matlab.mat.util.Preconditions.checkNotNull;

/**
 * A subclass of {@link Mat5Reader} that adds new filters that enable to read {@link DataCatalog} files partially.
 * <p>
 * The added filters include:
 * <ul>
 *     <li>{@link pl.cyfronet.insilicolab.server.model.data.reader.catalog.CatalogMat5Reader.CatalogStructFilter}
 *         - allows reading selected variables from matlab files, including those nested inside other structures.
 *         This filter was added to address the issue described in
 *         https://github.com/HebiRobotics/MFL/issues/69.</li>
 *     <li>{@link pl.cyfronet.insilicolab.server.model.data.reader.catalog.CatalogMat5Reader.CellFilter}
 *         - allows extracting only selected cells from a matlab file.</li>
 * </ul>
 * </p>
 * @author Mieszko
 */
public class CatalogMat5Reader extends Mat5Reader {

	public CatalogMat5Reader(Source source) {
		super(source);
	}

	/**
	 * Allows filtering structures that are nested inside other structures (they are not on the file root level). This
	 * is useful e.g. when reading large catalog files partially where column vectors are nested inside the main
	 * "catalog" structure. It enables to extract only selected indexes form selected catalog columns and skip other
	 * data to save memory.
	 * <p>{@link Mat5Reader} allows to read selected variables from matlab files using {@link EntryFilter} API but only
	 * if they are on the root level https://github.com/HebiRobotics/MFL/issues/69. </p>
	 */
	// This filter can be used for more file types than just DataCatalog. However, it would probably be more readable
	// to crate new filter for each file type that requires it.
	public interface CatalogStructFilter {

		/**
		 * @param catalogStructureColumnName For {@link DataCatalog} e.g. "field", "type, "val"
		 * @param rowNumber                  row of the catalog matlab file structure. Each row represents
		 *                                   DataCatalog.Column
		 * @param catalogColumnType          type of the column e.g. 3 means text column, 5 is time column
		 * @return true if the given field from catalog matlab file structure should be read, false if it should be
		 * skipped (probalby to save memory)
		 */
		boolean isAccepted(String catalogStructureColumnName, int rowNumber, Array catalogColumnType);
	}

	/**
	 * Set {@link CatalogStructFilter} when reading {@link DataCatalog} files.
	 */
	public CatalogMat5Reader setCatalogStructFilter(CatalogStructFilter catalogStructFilter) {
		this.catalogStructFilter = checkNotNull(catalogStructFilter);
		return this;
	}

	/**
	 * Allows extracting only selected cells from matlab file. Useful when reading partially large matlab files that
	 * contain arrays of cells. E.g. it helps to read partially {@link DataCatalog} files where string column is stored
	 * as array of cells
	 */
	public interface CellFilter {

		/**
		 * @return list of cell indexes that are accepted and should be read. Only cells with indexes in
		 * `acceptedIndexes` list are read and returned. Other cells will be skipped (probably to save memory)
		 */
		List<Integer> getAcceptedCellIndexes();
	}

	public CatalogMat5Reader setCellFilter(CellFilter cellFilter) {
		this.cellFilter = checkNotNull(cellFilter);
		return this;
	}

	/**
	 * @return size of the array that is currently processed
	 */
	private long getArraySizeInBytes() throws IOException {
		Mat5Tag tag = this.readTagWithExpectedType(Mat5Type.Matrix);
		return Casts.uint32(tag.getNumBytes());
	}

	@Override
	protected Array readCell(EntryHeader header) throws IOException {
		List<Integer> acceptedIndexes = cellFilter == null ? null : cellFilter.getAcceptedCellIndexes();

		// Subfield 4: Array of Cells Subelements. Stored in column major order
		int arraySize = acceptedIndexes == null ? header.getNumElements() : acceptedIndexes.size();

		int[] dimensions = acceptedIndexes == null ? header.getDimensions() : new int[] { acceptedIndexes.size(), 1 };
		final Array[] contents = new Array[arraySize];
		for (int readCellIdx = 0, acceptedCellIdx = 0; readCellIdx < header.getNumElements(); readCellIdx++) {
			if (acceptedIndexes == null || acceptedIndexes.contains(readCellIdx)) {
				contents[acceptedCellIdx++] = readNestedArray();
			} else {
				// Skip ignored cell
				long arraySizeInBytes = this.getArraySizeInBytes();
				source.skip(arraySizeInBytes);
			}
		}
		return createCell(dimensions, contents);
	}

	@Override
	protected Array[][] readValues(EntryHeader header, int numFields, String[] names) throws IOException {
		int numElements = header.getNumElements();
		final Array[][] values = new Array[numFields][numElements];
		for (int i = 0; i < numElements; i++) {
			for (int field = 0; field < numFields; field++) {
				//  Values passed to  catalogStructFilter when reading DataCatalog files partially:
				//
				//	Example catalog structure in matlab file:
				//	+-------+------+-------------------+--------------+-------------------+--------------+
				//	| field | type |        val        |     unit     |    description    |  fieldType   |
				//	+-------+------+-------------------+--------------+-------------------+--------------+
				//	| ID    |    3 | [411276x1 cell]   | char         | Event ID          | [0x0 double] |
				//	| Time  |    5 | [411276x1 double] | [0x0 double] | Event origin time | [0x0 double] |
				//	| Lat   |   25 | [411276x1 double] | deg          | Latitude          | [0x0 double] |
				//	| MD    |    4 | [411276x1 double] | [0x0 double] | Primary magnitude | Magnitude    |
				//	+-------+------+-------------------+--------------+-------------------+--------------+
				//
				//  catalogStructFilter.isAccepted(names[field], i, values[1][i])
				//
				// - `names` is array of column names ["field", "type", "val", "unit", +2 more]
				// - `names[field]` returns name of the column that is currently processed e.g. "val" column contains
				//    the data (number vectors for or array of string cells)
				// - `i` is a number of the row in catalog matlab file structure. Each row represents one
				//    DataCatalog.Column. From above example: 1 refers to `ID` column, 2 refers to `Time` column
				// - `values` is the whole catalog structure. From above example: `values[1][0]=3`.
				//   `values[1][0]` refers to type of `ID` column which is `3` (type=3 means text data)
				//   `values[1][1]` refers to type of `Time` column which is `5` (type=5 means time data)
				boolean isFieldAccepted = catalogStructFilter == null || catalogStructFilter.isAccepted(names[field], i,
						values[1][i]);
				if (isFieldAccepted) {
					values[field][i] = this.readNestedArray();
				} else {
					// Ship unwanted array
					long arraySizeInBytes = this.getArraySizeInBytes();
					source.skip(arraySizeInBytes);
				}
			}
		}
		return values;
	}

	@Override
	protected Mat5Reader createChildReader(Source source) {
		CatalogMat5Reader reader = new CatalogMat5Reader(source);
		reader.filter = this.filter;
		reader.mcos = this.mcos;
		reader.bufferAllocator = this.bufferAllocator;
		reader.catalogStructFilter = this.catalogStructFilter;
		reader.cellFilter = this.cellFilter;
		return reader;
	}

	private CatalogStructFilter catalogStructFilter = null;
	private CellFilter cellFilter = null;
}

```

### CODE REVIEW

**Comment by MieszkoMakuch** [comment]
I submitted a pull request that only exposes the fields needed for our use case. However, maybe it makes sense to expose more fields for consistency. If you do, just let me know which ones and I'll update the pull request.

If you think the current set of fields is good enough, we can leave it as is.

Thanks for checking out my contribution. Let me know if you have any questions or concerns!

**Comment by ennerf** [comment]
Thanks for putting this together. The only thing that jumped out on initial review is the `createChildReader(Source source)`. What do you think about splitting it into 2 methods, e.g., `createChildInstance(source)` and `child.copySettingsFrom(this)`? That way you can call `super.initChildReader()` without having to open up the mcos fields.

**Comment by MieszkoMakuch** [comment]
Ok!

I am not sure which methods should be overridable in your solution. I was thinking about something like this:

```java
protected Mat5Reader createChildReader(Source source) {
    Mat5Reader child = new Mat5Reader(source);
    child.copySettingsFrom(this);
    return child;
}

public void copySettingsFrom(Mat5Reader parent) {
    this.filter = parent.filter;
    this.mcos = parent.mcos;
    this.bufferAllocator = parent.bufferAllocator;
}
```

and then in subclass

```java
@Override
protected Mat5Reader createChildReader(Source source) {
	CatalogMat5Reader child = new CatalogMat5Reader(source);
	child.copySettingsFrom(this);
	child.catalogStructFilter = this.catalogStructFilter;
	child.cellFilter = this.cellFilter;
	return child;
}
```

**Comment by ennerf** [comment]
On second thought I think it's ok to merge as is and I'll do a minor consistency check and release when I get back from my current travels. Thanks for the contribution.

**Pull request merged**
